version: '2'
services:
  parser:
    image: nginx
    container_name: nginx
    ports:
    - 8009:80
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 192.168.2.237:24224
        tag: NGINX
